### model
model_name_or_path: models/epoch1

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### ddp
ddp_timeout: 180000000

### dataset
dataset_dir: data
dataset: mustc-sft2-sent-train
# llama3 base need set default
template: llama3
cutoff_len: 4096
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: output
# logging_steps: 50
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 0.0001
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
