#### model
model_name_or_path: /public/home/zhxgong/mzlv/llama3/8B-Instruct
adapter_name_or_path: /public/home/zhxgong/hxdou/0-Inbox/Refine/sent-stage1/output/checkpoint-3519
template: llama3
finetuning_type: lora
#
#### export
export_dir: models/llama3_lora_stage1
export_size: 2
export_device: gpu
export_legacy_format: false
