### model
model_name_or_path: /public/home/zhxgong/mzlv/llama3/8B-Instruct
adapter_name_or_path: /public/home/zhxgong/hxdou/0-Inbox/Refine/sent-multi-m1/output/checkpoint-7000

### method
stage: sft
do_predict: true
finetuning_type: lora
num_beams: 3

### dataset
dataset_dir: /public/home/zhxgong/hxdou/0-Inbox/Refine/data
dataset: sent-test-v4
template: llama3
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: predict_7000
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
